spring.application.name=shoestore

spring.datasource.url=jdbc:h2:mem:shoedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Cho phép Hibernate t?o schema
spring.jpa.hibernate.ddl-auto=update

# Trì hoãn ch?y data.sql cho ??n khi schema ???c t?o
spring.jpa.defer-datasource-initialization=true

# Hi?n th? SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

